In [2]:
import pandas as pd

marks = pd.Series([85,49,39,12])
print(marks)

0    85
1    49
2    39
3    12
dtype: int64

In [3]:
import numpy as np
arr = np.array([10,20,30])
s = pd.Series(arr)
print(s)

0    10
1    20
2    30
dtype: int64

In [4]:
marks  = pd.Series([85,90,54], index = ['Maths' , 'Science' , 'English'])
print(marks)

Maths      85
Science    90
English    54
dtype: int64

In [27]:
import numpy as np
s = pd.Series([10,20,30,40,50,60])
s.head(3)
s.sum()
s.sort_values()
s.unique()
s.mean()
s.max()
s.min()
s.tail()


print(s.apply(lambda x: x * 2))

0     20
1     40
2     60
3     80
4    100
5    120
dtype: int64

In [28]:
records = [
    {'Name': 'Aditi', 'Age' : 21},
    {'Name': 'Simran' , 'Age': 20},
]
df = pd.DataFrame(records)
print(df)

     Name  Age
0   Aditi   21
1  Simran   20

In [29]:
rows = [['Aditi' , 21] , ['Rohan' , 23]]
df  = pd.DataFrame(rows , columns = ['Name' , 'Age'])
print(df)

    Name  Age
0  Aditi   21
1  Rohan   23

In [31]:
# df_csv = pd.read_csv('student.csv')
# df_excel =  pd.read_excel("Student.xlsx",sheet_name='Sheet1')

In [ ]:
df = pd.read_excel('sales.xls')

In [ ]:
import pandas as pd

data = [
    ["Aman", 20, 85],
    ["Riya", 21, 90],
    ["Karan", 22, 78]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Marks"])

print(df)

df.head(1)
df.sample(2)
df.describe()
df.shape
df.columns
df.index
df.types
df('col').value_counts()
df('col').unique()

    Name  Age  Marks
0   Aman   20     85
1   Riya   21     90
2  Karan   22     78

Index(['Name', 'Age', 'Marks'], dtype='str')

In [ ]:
import pandas as pd
df.isnull()
df.isnull().sum()
df.notnull()

   Name   Age  Marks
0  True  True   True
1  True  True   True
2  True  True   True

In [39]:
df.dropna()
df.dropna(subset = ['Marks'])
df.dropna(how='all')

    Name  Age  Marks
0   Aman   20     85
1   Riya   21     90
2  Karan   22     78

In [50]:
df["Marks"] = df["Marks"].fillna(0)

In [43]:
# df['Gender'] = df['Gender'].replace({'M' : 'Male' , 'F' : 'Female'})

In [49]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Aman", "Neha", "Riya"],
    "Marks": [90, 85, 90, 95, 85]
}

df = pd.DataFrame(data)

print(df)
df.duplicated()
df.drop_duplicates()

   Name  Marks
0  Aman     90
1  Riya     85
2  Aman     90
3  Neha     95
4  Riya     85

   Name  Marks
0  Aman     90
1  Riya     85
3  Neha     95